### ISSUE TITLE
YouthSmokingAnalysis Unicode Error

### ISSUE THREAD

**Issue by uns1** [IngridWijaya3/PythonProject#1]
I get this error when I run my analysis file from the command prompt or through double clicking the file on windows (which is one way Lars might run it?). The error is orignating from our YouthSmokingAnalysis.py file.

![image](https://cloud.githubusercontent.com/assets/24362649/21211321/9efedd98-c250-11e6-8deb-457488daecf7.png)

If you run it through IDLE, you will not see this error. But if you double-click the file directly from the folder or run it through console/cmd, this is what shows up. -- Again I'm not sure how Lars will do it?

Thoughts/Suggestions?

**Comment by tonysantos** [comment]
try changing  the lines YouthSmokingAnalysis that load the files to something like this:
        self.ytsDataFrame = pandas.read_csv("YTS_Clean.csv", encoding="utf-8")
        self.taxRateDataFrame = pandas.read_csv("tax_data_all_cleaned.csv", encoding="utf-8")

Before we submit, we should upload to dropbox on sakai, download into a new directory, and make sure all code runs without errors.
